on:
  push:
    branches:
      - main

jobs:
  db_cicd:
      name: CD Example Production
      runs-on: ubuntu-latest
      steps:
        - name: Checkout My Code
          uses: actions/checkout@v4.2.2

        - name: SSH Remote
          uses: appleboy/ssh-action@v1
          with:
            host: ${{ secrets.SERVER_HOST }}
            username: ${{ secrets.SERVER_USERNAME }}
            password: ${{ secrets.SERVER_PASSWORD }}
            port: 22
            script: |
              sudo su
              echo "Berhasil konek cuyyyy"

              if [ -d "/home/edgar/CICD_DATABASE" ]; then
                cd /home/edgar/CICD_DATABASE
                echo "Berhasil masuk folder coyyy"
              else
                mkdir -p /home/edgar/CICD_DATABASE
                cd /home/edgar/CICD_DATABASE
                echo "Folder dibuat dan berhasil masuk folder coyyy"
              fi

              if [ -d ".git" ]; then
                git remote set-url origin https://${{ secrets.GIT_USERNAME }}:${{ secrets.GIT_PAT }}@github.com/Basic-Java-Maven-main.git
                git pull origin main
                echo "Git remote URL updated with credentials"
              else
                echo ".git directory not found"
                git clone https://${{ secrets.GIT_USERNAME }}:${{ secrets.GIT_PAT }}@github.com/Basic-Java-Maven-main.git .
                echo "Repository cloned with credentials"
              fi
              echo "Berhasil konek cuyyyy"